
schedule: "0 * * * *" # every hour is the default

image:
  repository: ghcr.io/isitar/backup-postgresql-k8s-cronjob
  pullPolicy: IfNotPresent
  tag: master

imagePullSecrets: []

secrets:
  POSTGRES_HOST:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  AZURE_STORAGE_CONNECTION_STRING: